name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Create Newman report directory
      run: mkdir testResults

    - name: Run Postman tests
      run: newman run COMPULIFEAPI.postman_collection.json -e COMPULIFE.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: RunReports
        path: testResults

