name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
        
    - name: Install Newman
      run: |
        npm install -g newman
        npm install newman-reporter-html

    - name: Create Newman report directory
      run: mkdir newman

    - name: Run Postman tests
      run: newman run COMPULIFEAPI.postman_collection.json -e COMPULIFE.postman_environment.json --reporters html --reporter-html-export newman/report.html

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: newman/

